### ISSUE TITLE
Audio issue when opening any release [with VB-Audio Virtual Cable]

### ISSUE THREAD

**Issue by szergej01** [MindStudioOfficial/ndiscopes#6] opened 2022-10-10 22:38 UTC
1. Download any release
2. Unzip to c:\ndiscopes
3. Start ndiscopes.exe

**Expected behavior**
Opens program

**Screenshots**
![image](https://user-images.githubusercontent.com/28932799/194962375-44e37d43-4041-489f-8f04-340163d95fcc.png)

**Hardware/Software**
- Win10 Pro 21H2
- ASUS GTX1080Ti

I cannot open the program without this error.

**Comment by MindStudioOfficial** [comment] 2022-10-10 22:58
The error appears because you don't seem to have any audio output devices.

The software trys to automatically choose the first audio device from the available ones which fails in your case.

This behavior is unintended and I will look into fixing this issue so you will be able to use the software without any audio devices present.

Thank you for reporting the bug.

**Comment by szergej01** [comment] 2022-10-10 23:14
We have a lot of output and input devices too in this computer. Shown on the attached screenshot, which is the default device. 

![image](https://user-images.githubusercontent.com/28932799/194965723-61122847-3b1c-4b86-a1f0-2e23c411d7f6.png)
![image](https://user-images.githubusercontent.com/28932799/194965869-019b3e78-1593-42da-924e-633546df1d6a.png)

**Comment by szergej01** [comment] 2022-10-10 23:16
In additional, I tried on another PC, and came out the same issue.

**Comment by MindStudioOfficial** [comment] 2022-10-11 21:32
Ok this sounds weird. What kind of Audio drivers have you installed? (Like Realtek or ASIO)

**Comment by MindStudioOfficial** [comment] 2022-10-11 21:40
I have a suspicion that it might have something to do with the default device. Does it work if you select a different default device in windows?

**Comment by MindStudioOfficial** [comment] 2022-11-01 12:39
We have identified the cause of this bug. Currently we get en error when trying to fetch the Icon for the "VB-Audio Virtual Cable" audio device which causes the displayed error message. 

A workaround would be to uninstall the "VB-Audio" drivers which should cause NDIScopes to startup normaly.

I am working on a fix for this bug.

**Comment by MindStudioOfficial** [comment] 2022-11-01 19:06
Fixed in release v0.7.3-beta

**Closed as completed by MindStudioOfficial** 2022-11-01 19:06 UTC
Labels: bug
