### ISSUE TITLE
Error MSB3073 while building

### ISSUE THREAD

**Issue by benkuper** [MindStudioOfficial/ndiscopes#8] opened 2022-08-24 18:54 UTC
**Describe the bug**
The build stops with many errors at the INSTALL part of the process (errors below)

**To Reproduce**
Open the project in VS Code (VS 2022 is installed)
run flutter upgrade
run flutter pub get
run flutter run -d windows

EDIT : also tried from a VS 2022 native command prompt (tested that setlocal is recognized), same error

**Expected behavior**
It builds :)

**Hardware/Software**
- Win 11 x64
- RTX 3060

**Additional context**
Log from the build

```
Launching lib\main.dart on Windows in debug mode...
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: The command "setlocal [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmEnd [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmErrorLevel [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]    
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: exit /b %1 [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]       
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :cmDone [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(157,5): error MSB3073: :VCEnd" exited with code 1. [D:\Desktop\ndiscopes\build\windows\INSTALL.vcxproj]
Building Windows application...                                         
Exception: Build process failed.
```

**Comment by MindStudioOfficial** [comment] 2022-08-24 19:19
Can you add the output of `flutter doctor -v`?

I have tried to reproduce the Issue but it works on my end.

I have VS Community 2022 **17.2.6** installed.

The main difference is that I am using Windows 10 instead of 11 and I have never tried to build on Windows 11.

I also found [this Issue](https://stackoverflow.com/questions/72061548/why-did-not-launch-windows-application) on Stackoverflow with the same error. However I am not sure if the answer provided makes sense.

Also in this issue https://github.com/flutter/flutter/issues/64419 The fix might be to just update Visual Studio.

**Comment by benkuper** [comment] 2022-08-24 19:58
Flutter doctor, after updating VS Studio, still not working

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-US)
    • Flutter version 3.0.5 at D:\Softwares\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\bkupe\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\bkupe\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\bkupe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by MindStudioOfficial** [comment] 2022-08-24 20:14
Can't see anything wrong here.

I highly suspect that this is unrelated to this specific repository.

Try `flutter clean` before `flutter run ...` maybe this helps.

Also something worth checking out:

> [Visual Studio 2022](https://visualstudio.microsoft.com/downloads/) When installing Visual Studio you need the “Desktop development with C++” workload installed for building windows, including all of its default components.

from the official [Flutter on Windows Guide](https://docs.flutter.dev/get-started/install/windows)

**Comment by MindStudioOfficial** [comment] 2022-08-24 20:17
If this is your first Flutter project you should try running the default sample project created when running `flutter create <projectname>` in an empty directory. This should create a simple app with a counter that increments when pressing the `+` button on screen. 


(Offtopic) Btw the URL on your GitGub Profile of you website is messed up :D

**Comment by benkuper** [comment] 2022-08-24 20:21
flutter clean didnt' help, it really seems that the deploy phase is the problem.
I can't actually test the command inside a prompt because it's multiline, not sure how I could test that outside the environment. VS is not telling much about the actual problem..

(Offtopic : thank you, fixed it :) you may be interested in the "Chataigne" project if you're working in the art sector ;) )

Also, to be honest, I'm mainly interesting in your implementation of NDI in flutter since it's a bit hard to get something workign off the shelf. I'm building a phone control app with NDI streaming, remote media playing / sound / vibration, sensor streaming, etc. for shows and art installation. But I tested your app and it's freaking cool !! I will recommend it for sure when I get the occasion !

**Comment by benkuper** [comment] 2022-08-24 20:36
Following on this,
I tried removing the problematic lines (keeping setlocal but removing the error check after that), it seems that the file is regenerated every time I build the project.
I can't find where this is generated but if somehow I can remove this, it would be interesting.

Also, I managed to test in an isolated terminal, there are some errors like "&amp;" not being recognized, replacing by "&" made it work, and then it complains about not recognizing "VCEnd" (which I think is defined during the build process).

So not sure what's happening, maybe some character escaping...

**Comment by MindStudioOfficial** [comment] 2022-08-24 20:43
It seems to only run a `cmake` command and then checking the error level. I am guessing you have `cmake` installed? (It should probably be included in VSC)

My NDI implementation is almost the same as the c++ version/examples provided with the official NDI SDK since I am using FFI to directly call the c-functions from dart code. 

Since I am a beginner in software development I am missing a lot of skills that are necessary to build highly complex desktop apps. Mainly I am struggeling with OpenGL right now. A lot of the computation in this app is done using NVIDIA CUDA. This is not because it is more performant but rather because that was the closest to the things I already knew.

The image processing part would probably benefit from an implementation using OpenGL/DirectX but I can't get around to learning these or incorporate them into my app. I see you seem to work a lot with c++ so you could probably implement the same thing in c++ with much better performance.

I would love to chat with you more about this topic so feel free to hit me up on Discord (MindStudio#6969) (will probably delete this later) I will gladly help you with the NDI implementation :D

My first look at Chataigne got me really exited because I work at a live streaming/TV/Video company. This kind of automation tool can be a real game changer in these kinds of environments. We already use StreamDecks for a lot of stuff.

**Comment by MindStudioOfficial** [comment] 2022-08-24 20:51
You should take a look at [this Stackoverflow thread](https://stackoverflow.com/questions/31457306/visual-studio-msb3073-error-exited-with-code-1).
This seems to have more promissing answers.

**Comment by benkuper** [comment] 2022-08-26 07:45
Still not working.. but I could try creating a new project and including everything in it since it seems like a project generation problem.
I have a question though : have you tried NDI sending ? I half managed to do it with another lib but nothing really relevant.. would be very interested if you got anything that could help me ;)

Thank you again for this !

**Comment by MindStudioOfficial** [comment] 2022-08-26 12:51
So another project works fine?

Yes I have tried sending. In a seperate testing project I was able to render a part of the UI as an Image and send it to OBS via NDI. Worked quite well actually, even including alpha channel with transparency where no UI elements covered the screen.
I can't really remember what the latency was but I think it was just a few milliseconds.

**Comment by MindStudioOfficial** [comment] 2022-08-26 12:56
OOOOHH I think I know why it doesn't work!!!

For licensing reasons I have not included the NDI SDK DLL in the repo. (See Get Started in README.md) 
Usually this would not be a problem when building since it only accesses the file when starting but I recently added 
this line: https://github.com/MindStudioOfficial/ndiscopes/blob/fdfdefc76e4b70bd8663d8ed03b62c53d59082f7/windows/CMakeLists.txt#L103
which automatically moves this dll to the Release folder. Since it is not present at the specified path it will of course fail.

Just download the NDI Windows SDK and add the file to the other DLLs in the `bin` folder.

**Comment by benkuper** [comment] 2022-08-26 12:59
Interesting, I'll check that ;)
Would you be ok with sharing the sending test NDI project ?
I'm struggling to send from android in NDI, I ended up implementing a custom websocket streaming system because I was short on time, but the rate is quite poor and I'd really like the whole system to be more universal.
That would help me a lot to check how it's done, I suspect porting to android should not be the hard part since it's the same SDK.

Thank you so much !

**Comment by MindStudioOfficial** [comment] 2022-08-26 13:06
I haven't tried it on Android and I think there might be small differences to the different SDKs. The Project is just a local folder on some hard drive so I would have to find that first. 

I would prefer if we could continue this (slightly offtopic) conversation somewhere else outside this Issue since I am going to close it if the fix works. Then I can send you more specific stuff regarding your implementation or we could work together on an android sample project. (Text only chat is still fine though :D)

**Comment by benkuper** [comment] 2022-08-26 13:11
Copying the dll file in the bin folder works ! Congrats :)
Also I realized I had read the readme a bit too fast, everything's in there.
No regrets though, we got to share a bit more than just this problem ;)
If you got anything that could kickstart me for NDI sending I would be super happy !
Have a great day

**Comment by MindStudioOfficial** [comment] 2022-08-26 14:07
Nice!
I will update the readme since the line where you have to copy the bin folder to the release folder is no longer accurate since I added the line in the CMakeList.txt

**Closed by MindStudioOfficial** 2022-08-26 14:07 UTC
Labels: build error
